name: Build under Windows

on: pull_request

jobs:
  build:
    name: Build under Windows
    runs-on: windows-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
          cache: gradle

      # See: https://github.com/al-cheb/configure-pagefile-action
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3

      - name: Build project and run tests
        shell: cmd
        # For the reason on `--no-daemon` see https://github.com/actions/cache/issues/454
        run: gradlew.bat build --stacktrace --no-daemon -i
